/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts/{aid}/wallets/cards": {
    /**
     * Create a new card
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     */
    post: operations["aid_cards_post"];
  };
  "/accounts/{aid}/wallets/cards/{card_id}": {
    /**
     * Get all details about a card
     *
     * scopes:
     * - admin:wallets
     * - read:wallets
     */
    get: operations["aid_cards_cardid_get"];
  };
  "/accounts/{aid}/wallets/cards/{card_id}/tokens": {
    /**
     * Create a temporary `token` (also referred as Card Code)
     * for the card, an temporary alias that must be used when
     * when creating a drawdown transaction
     *
     * The token can be stored in a barcode to allow use of virtuell card
     * in purchase in POS or webstore
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     */
    post: operations["aid_cards_cardid_token_post"];
  };
  "/accounts/{aid}/wallets/cards/{card_id}/transactions": {
    /**
     * Retrieve a list of Card's Transaction based on card id
     *
     * scopes:
     * - admin:wallets
     * - read:wallets
     */
    get: operations["aid_cards_cardid_transactions_tid_get"];
  };
  "/accounts/{aid}/wallets/customers/{customer_id}/cards": {
    /**
     * Get the cards active for a customer
     *
     * scopes:
     * - admin:wallets
     * - read:wallets
     * - user:wallets
     */
    get: operations["aid_customers_cid_cards_get"];
  };
  "/accounts/{aid}/wallets/customers/{customer_id}/cards/{card_id}": {
    /**
     * Get all details about a customer card
     *
     * scopes:
     * - admin:wallets
     * - read:wallets
     * - user:wallets
     */
    get: operations["aid_customers_cid_card_cid_get"];
  };
  "/accounts/{aid}/wallets/info": {
    /**
     * Get details about a card, including the current balance and available
     * funds. No details will be returned for expired tokens
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     * - write:wallets:/info
     */
    post: operations["aid_cards_token_post"];
  };
  "/accounts/{aid}/wallets/transactions": {
    /**
     * Create a transaction against a Card using `token` or `card_id`.
     * If the Transactions is created as pending, the value will
     * be locked until it is either captured or voided. Transaction ID must
     * be used when capturing or voiding a transaction.
     *
     * > Using **`card_id`** or creating a **`fund`** transaction requires
     * > authorization scope `admin:wallets` or `write:wallets`
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     * - write:wallets:/transactions
     */
    post: operations["aid_cards_transactions_post"];
  };
  "/accounts/{aid}/wallets/transactions/{transaction_id}/capture": {
    /**
     * Capture a pending Transaction, thereby collection the amount
     * withheld by the pending transaction.
     *
     * Option to specify an amount that should be captured.
     * Defaults to capture the full transaction.
     * When the amount specified is less than the reserved/pending,
     * the remaining amount will still be reserved/pending and can be captured later.
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     * - write:wallets:/transactions
     */
    post: operations["aid_cards_cardid_transactions_capture_post"];
  };
  "/accounts/{aid}/wallets/transactions/{transaction_id}/void": {
    /**
     * Void a pending Transaction by unlocking the amount
     * withheld by the pending transaction
     *
     * scopes:
     * - admin:wallets
     * - write:wallets
     * - write:wallets:/transactions
     */
    post: operations["aid_cards_cardid_transactions_void_post"];
  };
}

export interface definitions {
  CardProperties: {
    /**
     * @description The card id you have defined for the card.
     * (must not have trailing or leading spaces)
     */
    card_id: string;
    /**
     * @description The customer id you have defined as the owner
     * of the card. (must not have trailing or leading spaces)
     */
    customer_id?: string;
    /** @description Display name for the card */
    name?: string;
  };
  ImmutableEntity: {
    /**
     * Format: uuid
     * @description An UUID that uniquely identifies the resource
     */
    id?: string;
    /**
     * Format: date-time
     * @description The date-time when the resource was created
     */
    created_at?: string;
    /**
     * @description The ID of the user/client that created the resource
     *
     * @example 1c92f7e1-2897-4d46-bdcc-c127a914fb4e
     */
    created_by?: string;
  };
  Metadata: {
    /**
     * @description A key-value JSON object to store any additional
     * information. The dintero_* namespace for keys
     * is reserved
     *
     * @example {
     *   "order_id": "xk39592f"
     * }
     */
    metadata?: { [key: string]: unknown };
  };
  Operation: {
    /**
     * @description Monetary amount in smallest unit for the currency
     *
     * @example 50000
     */
    amount: number;
    /**
     * @description The three-character ISO-4217 currency.
     * https://en.wikipedia.org/wiki/ISO_4217
     *
     * @example NOK
     * @enum {string}
     */
    currency: "NOK";
  };
  CardBalance: {
    /**
     * @description The balance, including amount locked by pending transaction.
     * Monetary amount in smallest unit for the currency
     *
     * @example 50000
     */
    amount_balance?: number;
    /**
     * @description The amount available for drawdown
     * (exclusive amount locked by pending transactions).
     * Monetary amount in smallest unit for the currency
     *
     * @example 50000
     */
    amount_available?: number;
  };
  CardActivePeriod: {
    /**
     * Format: date-time
     * @description Optional time when the card is activated. No `drawdown` transaction
     * will be allowed before if set. (`fund` transaction is allowed)
     */
    active_from?: string;
    /**
     * Format: date-time
     * @description Optional expiration time for the card. No transaction will be
     * allowed on an expired card
     */
    expires_at?: string;
  };
  Card: definitions["CardProperties"] &
    definitions["ImmutableEntity"] &
    definitions["Metadata"] &
    definitions["Operation"] &
    definitions["CardBalance"] &
    definitions["CardActivePeriod"];
  /** @description specify the format for to generate */
  Format: {
    /**
     * @description the length of the token (exclusive length of prefix)
     *
     * @default 36
     */
    length?: number;
    /**
     * @description prefix the token, the lenght of prefix will affect
     * the total length of the token
     *
     * @example DINCARD:
     */
    prefix?: string;
    /**
     * @description allow characters like `@#$%` in token created
     * @default true
     */
    symbols?: boolean;
    /**
     * @description allow characters like `123456` in token created
     * @default true
     */
    numbers?: boolean;
    /** @description allow characters like `acbABC` in token created */
    characters?: boolean;
    /**
     * @description Include token as base64 encoded barcode image
     *
     * @default false
     */
    barcode?: boolean;
  };
  /** @description Specify how pin should be generated */
  PinGenerator: {
    format?: definitions["Format"];
    pin?: {
      /** @example 012345 */
      value?: string;
      /**
       * @description Code 128 barcode representation of the pin value. A base64 encoded
       * image in format `data:[<mime type>][;charset=<charset>][;base64],<encoded data>`
       *
       * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA...
       */
      barcode_128?: string;
    };
  };
  /** @description Specify how token should be generated */
  TokenGenerator: {
    format?: definitions["Format"] & unknown;
    /**
     * @description The token can only be used to create one transaction, card lookup by
     * token will be available until token expires by date
     *
     * @default true
     */
    expires_after_transaction?: boolean;
    /**
     * @description The lifetime in seconds for the card token.  For
     * example, the value "3600" denotes that the token will
     * expire in one hour from the time the response was generated.
     */
    expires_in: number;
    token?: {
      /** @example DINCARD:6ccfec5d-3a53-47de-910a-97d6dda22e5f */
      value?: string;
      /**
       * @description Code 128 barcode representation of the token value. A base64 encoded
       * image in format `data:[<mime type>][;charset=<charset>][;base64],<encoded data>`
       *
       * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIA...
       */
      barcode_128?: string;
    };
  };
  Error: {
    error: {
      /** @description The code used to identify the error/warning */
      code?: string;
      /** @description The nested error(s) encountered during validation */
      errors?: { [key: string]: unknown }[];
      /** @description The human readable description of the error/warning */
      message: string;
    };
  };
  TokenList: {
    tokens?: {
      /**
       * Format: date-time
       * @description expiration time for the token
       */
      expires_at?: string;
      /**
       * @description masked token code
       * @example DINCARD:********-****-****-91**-*******22e5f
       */
      masked_code?: string;
    }[];
  };
  CardDetails: definitions["Card"] & definitions["TokenList"];
  BaseOperation: {
    /**
     * @description Unique ref ID provided by the client to support safely retrying
     * requests without accidentally performing the same operation twice
     *
     * All card transaction must have a unique ref ID, but it is not
     * required that the ref ID is globally unique.
     */
    ref_id: string;
  };
  Token: definitions["ImmutableEntity"] &
    definitions["Metadata"] &
    definitions["BaseOperation"] &
    definitions["TokenGenerator"];
  TransactionInput: definitions["ImmutableEntity"] &
    definitions["Metadata"] &
    definitions["BaseOperation"] &
    definitions["Operation"];
  Transaction: definitions["TransactionInput"] & {
    /**
     * @description The type of the Transaction:
     *   - *fund*: the amount has been funded to the card
     *   - *drawdown*: the amount has been drawn from the card
     *   - *pending_capture*: the amount has been locked until it is either captured or voided
     *   - *voided*: the amount locked by pending Transaction is unlocked
     *
     * @enum {string}
     */
    type?: "drawdown" | "pending_capture" | "voided" | "fund";
    /**
     * Format: uuid
     * @description The ID of the original Transaction for a void or
     * capture transaction
     */
    parent_id?: string;
  };
  CustomerCard: definitions["ImmutableEntity"] &
    definitions["Metadata"] &
    definitions["CardActivePeriod"] &
    definitions["CardProperties"];
  CustomerCardState: definitions["CustomerCard"] &
    definitions["TokenList"] &
    definitions["CardBalance"] & {
      /**
       * @description Three-character ISO-4217 currency.
       * https://en.wikipedia.org/wiki/ISO_4217
       *
       * @example NOK
       * @enum {string}
       */
      currency?: "NOK";
    };
  TokenCode: {
    /** @description temporary token for a Card */
    token: string;
    /** @description PIN for the Card */
    pin?: string;
  };
  CardByIdOrToken: {
    /** @description **required** if `card_id` is not set (cannot be combined with `card_id`) */
    token?: string;
    /** @description **required** if `token` is not set (cannot be combined with `token`) */
    card_id?: string;
  };
  OptionalAmount: {
    /**
     * @description Monetary amount in smallest unit for the currency
     *
     * @example 50000
     */
    amount?: number;
  };
}

export interface parameters {
  /**
   * Format: ^[PT]{1}\d{8}$
   * @description An id that uniquely identifies the account.
   */
  accountId: string;
  /**
   * @description The card id you have defined for the card.
   * (must not have trailing or leading spaces)
   */
  cardId: string;
  /**
   * @description The customer id you have defined for the customer.
   * (must not have trailing or leading spaces)
   */
  customerId: string;
  /**
   * @description A limit on the number of objects to be returned. Limit can range
   * between 1 and 100 items, and the default is 10 items.
   *
   * @default 10
   */
  limit: number;
  /**
   * @description cursor for use in pagination. starting_after is an object ID
   * that defines your place in the list. For instance, if you make
   * a list request and receive 100 objects, end the result contains
   *   `paging_token=pt1`, your subsequent call can include
   * `starting_after=pt1` in order to fetch the next page of the list.
   */
  startingAfter: string;
  /**
   * Format: uuid
   * @description An id that uniqely idetifies a transaction
   */
  transactionId: string;
}

export interface responses {
  /** Bad / Invalid request */
  BadRequest: {
    schema: definitions["Error"];
  };
  /** Access forbidden, invalid JWT token was used */
  AccessForbidden: {
    schema: definitions["Error"];
  };
  /** Forbidden */
  Forbidden: {
    schema: definitions["Error"];
  };
  /** Unexpected Error */
  ServerError: {
    schema: definitions["Error"];
  };
  /** Resource was not found */
  NotFound: {
    schema: definitions["Error"];
  };
}

export interface operations {
  /**
   * Create a new card
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   */
  aid_cards_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
      };
      body: {
        /** card details */
        data: definitions["Card"] & {
          pin?: definitions["PinGenerator"];
          card_token?: definitions["TokenGenerator"];
        };
      };
    };
    responses: {
      /** Card created */
      200: {
        schema: definitions["Card"] & {
          pin?: definitions["PinGenerator"];
          card_token?: definitions["TokenGenerator"];
        };
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      500: responses["ServerError"];
    };
  };
  /**
   * Get all details about a card
   *
   * scopes:
   * - admin:wallets
   * - read:wallets
   */
  aid_cards_cardid_get: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /**
         * The card id you have defined for the card.
         * (must not have trailing or leading spaces)
         */
        card_id: parameters["cardId"];
      };
    };
    responses: {
      /** Card details */
      200: {
        schema: definitions["CardDetails"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Create a temporary `token` (also referred as Card Code)
   * for the card, an temporary alias that must be used when
   * when creating a drawdown transaction
   *
   * The token can be stored in a barcode to allow use of virtuell card
   * in purchase in POS or webstore
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   */
  aid_cards_cardid_token_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /**
         * The card id you have defined for the card.
         * (must not have trailing or leading spaces)
         */
        card_id: parameters["cardId"];
      };
      body: {
        /** token details */
        data: definitions["Metadata"] &
          definitions["BaseOperation"] &
          definitions["TokenGenerator"];
      };
    };
    responses: {
      /** Token created */
      200: {
        schema: definitions["Token"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Retrieve a list of Card's Transaction based on card id
   *
   * scopes:
   * - admin:wallets
   * - read:wallets
   */
  aid_cards_cardid_transactions_tid_get: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /**
         * The card id you have defined for the card.
         * (must not have trailing or leading spaces)
         */
        card_id: parameters["cardId"];
      };
    };
    responses: {
      /** Transcation list */
      200: {
        schema: definitions["Transaction"][];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Get the cards active for a customer
   *
   * scopes:
   * - admin:wallets
   * - read:wallets
   * - user:wallets
   */
  aid_customers_cid_cards_get: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /**
         * The customer id you have defined for the customer.
         * (must not have trailing or leading spaces)
         */
        customer_id: parameters["customerId"];
      };
      query: {
        /**
         * A limit on the number of objects to be returned. Limit can range
         * between 1 and 100 items, and the default is 10 items.
         */
        limit?: parameters["limit"];
        /**
         * cursor for use in pagination. starting_after is an object ID
         * that defines your place in the list. For instance, if you make
         * a list request and receive 100 objects, end the result contains
         *   `paging_token=pt1`, your subsequent call can include
         * `starting_after=pt1` in order to fetch the next page of the list.
         */
        starting_after?: parameters["startingAfter"];
      };
    };
    responses: {
      /** Card details */
      200: {
        schema: definitions["CustomerCard"][];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Get all details about a customer card
   *
   * scopes:
   * - admin:wallets
   * - read:wallets
   * - user:wallets
   */
  aid_customers_cid_card_cid_get: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /**
         * The customer id you have defined for the customer.
         * (must not have trailing or leading spaces)
         */
        customer_id: parameters["customerId"];
        /**
         * The card id you have defined for the card.
         * (must not have trailing or leading spaces)
         */
        card_id: parameters["cardId"];
      };
    };
    responses: {
      /** Card details */
      200: {
        schema: definitions["CustomerCardState"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Get details about a card, including the current balance and available
   * funds. No details will be returned for expired tokens
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   * - write:wallets:/info
   */
  aid_cards_token_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
      };
      body: {
        data: definitions["TokenCode"];
      };
    };
    responses: {
      /** Card info details */
      200: {
        schema: definitions["Card"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Create a transaction against a Card using `token` or `card_id`.
   * If the Transactions is created as pending, the value will
   * be locked until it is either captured or voided. Transaction ID must
   * be used when capturing or voiding a transaction.
   *
   * > Using **`card_id`** or creating a **`fund`** transaction requires
   * > authorization scope `admin:wallets` or `write:wallets`
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   * - write:wallets:/transactions
   */
  aid_cards_transactions_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
      };
      body: {
        /** transaction details */
        data: definitions["CardByIdOrToken"] &
          definitions["TransactionInput"] & {
            /**
             * @default drawdown
             * @enum {string}
             */
            type?: "drawdown" | "fund";
            /**
             * @description If true, the transaction will be created as pending, i.e.
             * the value will be locked until it is either captured or
             * voided.
             *
             * > Only supported when creating a `drawdown` transaction.
             *
             * @default false
             */
            pending?: boolean;
          };
      };
    };
    responses: {
      /** Transaction created */
      200: {
        schema: definitions["Transaction"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Capture a pending Transaction, thereby collection the amount
   * withheld by the pending transaction.
   *
   * Option to specify an amount that should be captured.
   * Defaults to capture the full transaction.
   * When the amount specified is less than the reserved/pending,
   * the remaining amount will still be reserved/pending and can be captured later.
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   * - write:wallets:/transactions
   */
  aid_cards_cardid_transactions_capture_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /** An id that uniqely idetifies a transaction */
        transaction_id: parameters["transactionId"];
      };
      body: {
        /** capture details */
        data: definitions["Metadata"] &
          definitions["BaseOperation"] &
          definitions["OptionalAmount"];
      };
    };
    responses: {
      /** Transaction created */
      200: {
        schema: definitions["Transaction"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
  /**
   * Void a pending Transaction by unlocking the amount
   * withheld by the pending transaction
   *
   * scopes:
   * - admin:wallets
   * - write:wallets
   * - write:wallets:/transactions
   */
  aid_cards_cardid_transactions_void_post: {
    parameters: {
      path: {
        /** An id that uniquely identifies the account. */
        aid: parameters["accountId"];
        /** An id that uniqely idetifies a transaction */
        transaction_id: parameters["transactionId"];
      };
      body: {
        /** void details */
        data: definitions["Metadata"] & definitions["BaseOperation"];
      };
    };
    responses: {
      /** Transaction voided */
      200: {
        schema: definitions["Transaction"];
      };
      400: responses["BadRequest"];
      401: responses["AccessForbidden"];
      403: responses["Forbidden"];
      404: responses["NotFound"];
      500: responses["ServerError"];
    };
  };
}

export interface external {}
